/* _GlobalPrefix_ */
this.gbar_=this.gbar_||{};(function(_){var window=this;
/* _Module_:lat */
try{
var sy=function(a){_.D(this,a,0,-1,null)};_.y(sy,_.C);var ty=function(a){_.D(this,a,0,-1,null)};_.y(ty,_.C);var uy=function(a){var b=a.length,c=_.n(a)?a.split(""):a;for(--b;0<=b;b--)if(b in c&&_.rp.call(void 0,c[b],b,a))return b;return-1},vy=function(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c},wy=function(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c},xy=function(){};_.y(xy,Error);
var yy=function(a,b,c,d,e,f){_.fq.call(this,a,d);this.F=e;this.o=f||null;this.B=this.b.getAttribute("data-pid");this.D=b;this.C=c;_.tj(this,this.b,(0,_.u)(this.G,this));if(a=_.O("gb_2",this.b))a=a.style.backgroundPosition.split(" "),_.Up("#"+this.b.id+" .gb_2::before{left:"+a[0]+";top:"+a[1]+"}")};_.y(yy,_.fq);
yy.prototype.G=function(a){a=a.o;var b={t:this.B,l:this.D};if(a){var c=a.getAttributeNode("data-ved");c&&c.value&&(b.ved=c.value);_.Wg(a,"gbpq")&&zy(this,a)}this.F.log(1,b);this.o&&(a=new _.xi,b=_.Yc(this.B),_.la(b)&&!(0,window.isNaN)(b)&&_.T(a,15,b),this.o.log(8,a))};
var zy=function(a,b){if(a.C)window.o&&_.Op(b,window.o.vj(b.href));else if(window.document.forms[0]&&window.document.forms[0].q){var c=(window.document.forms[0].q||"").value;c&&_.Op(b,b.href.replace(/([?&])q=[^&]*|$/,function(a,b){return(b||"&")+"q="+(0,window.encodeURIComponent)(c)}))}else a.w.log(new xy)},Ay=function(a,b,c,d,e,f){for(var g=[],k=0;k<a.length;k++)g.push(new yy(a[k],b,c,d,e,f));return g},By=function(a,b,c,d,e){_.st.call(this,a,"aw",c,d,!0,e);this.C=Ay(_.Qp("gb_O",this.b),2,b,c,d,e);
this.H=29;this.fa=30;this.qa=29;this.Ba=30;this.Ma()};_.y(By,_.st);By.prototype.P=function(){By.J.P.call(this);for(var a=0;a<this.C.length;a++)this.C[a].ha();this.C=null};var Cy=function(a,b,c,d){_.fq.call(this,a,c);this.o=Ay(_.Qp("gb_P",this.b),1,b,c,d)};_.y(Cy,_.fq);Cy.prototype.P=function(){Cy.J.P.call(this);for(var a=0;a<this.o.length;a++)this.o[a].ha();this.o=null};var Dy=function(a){this.ia=a;this.b={}};
Dy.prototype.$a=function(){var a=vy(this.b,function(a){return null!==a});a=_.sg(a)?null:a;a=[this.ia,this.o,a];var b=uy(a);return a=a.slice(0,b+1)};Dy.prototype.toString=function(){var a=this.$a();return"("+(0,_.ya)(a,function(a){return(new _.qe).o(a)}).join(",")+")"};Dy.prototype.getId=function(){return this.ia};var Ey=function(){Dy.call(this,"image-search")};_.y(Ey,Dy);var Fy=function(){Dy.call(this,"maps")};_.y(Fy,Dy);var Gy=function(){Dy.call(this,"photos")};_.y(Gy,Dy);
var Hy=function(){Dy.call(this,"url")};_.y(Hy,Dy);var Iy=function(){Dy.call(this,"video-search")};_.y(Iy,Dy);var Jy=function(){Dy.call(this,"web")};_.y(Jy,Dy);
var Ky=function(){this.o=_.n(void 0)?new Dy(void 0):void 0;this.b=[];this.w={}},Ly=function(a){switch(a){case "image-search":return new Ey;case "maps":return new Fy;case "photos":return new Gy;case "url":return new Hy;case "video-search":return new Iy;case "web":return new Jy}return new Dy(a)},My=function(a){return"("+(0,_.ya)(a.b,function(a){return a.toString()}).join(",")+")"},Ny=function(a){a=vy(a.w,function(a){return null!==a});return(a=_.sg(a)?null:a)?(new _.qe).o(wy(a,function(a){return a.toString()})):
""};Ky.prototype.toString=function(){if(this.o){var a=["{root:",this.o.toString(),",items:",My(this)],b=Ny(this);b&&(a.push(",options:"),a.push(b));a.push("}");return a.join("")}return My(this)};var Oy=function(a){this.A=a||"https://docs.google.com/picker";this.o=new Ky};Oy.prototype.o=null;var Py=function(a,b){a.o.b.push(_.n(b)?Ly(b):b);return a},Qy=function(a){Oy.call(this,a)};_.y(Qy,Oy);
var Sy=function(a){Oy.call(this,a);this.b=new _.ih(this.A);Ry(this,"gadgets");(a=window.location.origin)||(a=window.location.protocol+"//"+window.location.host);a&&_.xh(this.b,"origin",a);this.w=[]};_.y(Sy,Qy);Sy.prototype.getHeight=function(){return this.B};Sy.prototype.getRelayUrl=function(){return this.b.La.get("relayUrl")};var Ry=function(a,b){_.xh(a.b,"protocol",b);return a};Sy.prototype.setRelayUrl=function(a){_.xh(this.b,"relayUrl",a);return this};
Sy.prototype.setTitle=function(a){_.xh(this.b,"title",a);return this};var Ty=function(a){a.w.length&&_.xh(a.b,"pp",(new _.qe).o(a.w));return _.xh(a.b,"nav",My(a.o)).clone()},Uy=function(a){Dy.call(this,"upload");this.b.query=a};_.y(Uy,Dy);var Vy=function(a,b){Dy.call(this,"webcam");a&&(this.b.type=a);b&&(this.b.query=b)};_.y(Vy,Dy);
var Wy=/.*?\/(\d{6,})\/(?:\1\/)*(.*\/?)/,Xy=function(a,b,c,d,e){_.z.call(this);this.X=d;this.lb=e;this.b=_.O("gb_Qb",a);this.Z=_.Qp("gb_Hb");this.N=_.O("gb_6b",a);this.ja=_.I(_.E(b,20));this.ca=_.I(_.E(b,16));this.D=new _.bq(d,this);this.ba=_.I(_.E(b,1));this.ea=_.I(_.E(b,4));this.fa=_.I(_.E(b,2));this.ma=_.I(_.E(b,24));this.qa=_.I(_.E(b,27));this.Ha=_.I(_.E(b,28));this.vb=_.H(_.E(b,3));this.ub=_.H(_.E(b,22));this.Ea=_.H(_.E(b,5));this.w=_.H(_.E(b,32));if(this.M=_.H(_.E(b,33)))this.C=_.dn(a);this.T=
this.O=!1;this.S=_.I(_.E(b,13));this.Ba=_.I(_.E(c,6));this.tb=_.I(_.E(c,7));this.$=_.I(_.E(b,8));this.kb=_.E(b,21)||this.$;this.Qb=_.I(_.E(b,25));this.Ob=_.I(_.E(b,26));this.A=[];this.o=[];this.K=!1;this.B=null;this.H={};a=_.Qp("gb_Sb",this.b);for(c=0;c<a.length;c++)if(e=_.O("gb_4b",a[c]),d=_.O("gb_2b",a[c]),e&&d){if(_.ac&&null!==e&&"innerText"in e)e=e.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var f=[];_.Zs(e,f,!0);e=f.join("")}e=e.replace(/ \xAD /g," ").replace(/\xAD/g,"");e=e.replace(/\u200B/g,
"");_.ac||(e=e.replace(/ +/g," "));" "!=e&&(e=e.replace(/^\s*/,""));this.H[e]=d.getAttribute("data-src")||d.src}this.F=!1;this.G=null;this.W=_.H(_.E(b,14));this.ra=_.I(_.E(b,15));this.V=2E4;this.Rb=_.H(_.E(b,29))&&!1};_.y(Xy,_.z);Xy.prototype.P=function(){Xy.J.P.call(this);delete this.b;delete this.N;this.A=null;this.o=[];this.D.ha()};
var az=function(a,b,c){_.dg(a.b,_.pc);a.A=[];Yy(a,b,c);Zy(a);$y(a,!1)},Yy=function(a,b,c){if(a.w)if(c){if(0!=a.o.length)for(b=a.o,a.o=[],c=0;c<b.length;c++)bz(a,b[c])}else a.o=[],null!=b&&a.w&&a.F&&(b?cz(a):a.K=!0);else a.o=[]},ez=function(a,b){var c=b.ab;b.$e?c=a.ba.replace("%1$s",b.ab):b.af?c=a.ea.replace("%1$s",b.ab):2==b.type&&(c=a.fa);var d=2==b.type?b.ab:c,e=b.pf;e?a.H[d]=e:e=a.H[d]?a.H[d]:1==b.type?"https://ssl.gstatic.com/gb/images/silhouette_48.png":"https://ssl.gstatic.com/gb/images/pluspages_48.png";
d=_.S("IMG",{"class":"gb_2b gb_Db",src:e,alt:2==b.type?a.ca:a.ja});e=_.S("DIV","gb_3b",b.name||b.ab);c=_.S("DIV",{"class":"gb_4b",dir:"ltr"},c);e=[e,c];c=[];if(b.$b){var f=_.S("DIV","gb_5b",a.ma);e.push(f);f=_.S("BUTTON",["gb_Wb","gb_Xb"],a.qa);var g=_.S("BUTTON",["gb_Wb","gb_Zb"],a.Ha);f.setAttribute("aria-hidden","true");g.setAttribute("aria-hidden","true");var k=_.S("DIV","gb_Vb");a.D.L(f,"click",(0,_.u)(a.Nb,a,b.ab));a.D.L(k,"click",a.Pb);c.push(f);c.push(g);dz(a,f);dz(a,g);c.push(k)}e=_.S("DIV",
"gb_Ub",e);c.push(d);c.push(e);d=_.S("A","gb_Sb",c);b.$b&&(a.D.L(d,"keydown",a.Na),_.P(d,"gb_Pb"));if(c=b.Qd)a.W&&2==b.type&&(f=b.id,e=c.match(Wy))&&(f=f||e[1],g=e[2],k=window.location.href,c=(e=k.match(Wy))?k.replace(new RegExp(e[1],"g"),f):c.replace(g,a.ra)),_.Op(d,c);if(c=(c=1==b.type?a.vb:a.ub)||a.W&&2==b.type)d.target="_blank",_.Eb&&(d.rel="noreferrer");if(b.Ze&&((c=_.O("gb_0b",a.b))&&_.R(c,"gb_0b"),_.P(d,"gb_0b"),b.name))for(c=0;c<a.Z.length;c++)_.dg(a.Z[c],_.cg(b.name));return d},dz=function(a,
b){a.D.L(b,_.Eg(27)?"keypress":"keyup",a.Ga)},fz=function(a,b,c,d){d&&a.w&&0!=a.o.length?a.b.insertBefore(b,_.O("gb_Pb",a.b)):a.b.appendChild(b);a.A.push(b);Zy(a);2==c&&$y(a,!0)},$y=function(a,b){_.ln(a.N,"gb_bb",!b);a.N.setAttribute("aria-hidden",!b+"")},Zy=function(a){var b=a.b.children.length;b=0==b||1==b&&_.Wg(a.b.firstChild,"gb_0b");_.ln(a.b,"gb_bb",b);a.b.setAttribute("aria-hidden",b+"")},cz=function(a){!a.Ea||a.F&&!a.w||(gz(a,!0,!0),a.F||_.bt(a.X,window,"message",(0,_.u)(a.Fa,a)),hz(a),a.G=
iz(a.S),a.F=!0)},jz=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};
Xy.prototype.Fa=function(a){if(0==this.o.length||!this.w){a=a.b;var b=a.origin,c=this.S.match(_.bf);b=b.match(_.bf);if(c[3]==b[3]&&c[1]==b[1]&&c[4]==b[4])try{b:{var d=a.data;if(d){a=null;try{a=new _.Nn(d?JSON.parse(d):null)}catch(p){try{var e=JSON.parse(d),f=_.Zm[e[0]];if(!f)throw Error("d`"+e[0]);a=new f(e)}catch(q){var g=null;break b}}g=_.oi(a,_.Ln,1)}else g=null}if(g&&0!=g.length){this.w||az(this);for(d=0;d<g.length;++d)bz(this,g[d]);var k=!0}else k=!1;k&&(this.K=!1,gz(this,!1,!0),hz(this))}catch(p){this.X.log("Error occured in ogb.identity.MultiLogin.prototype.processAccountsInfo_ "+
(p.name?p.name:""))}}};
var bz=function(a,b){var c={valid:!1};if(b){c.type=_.E(b,1);c.ab=_.I(_.E(b,3));c.$e=_.H(_.E(b,6));c.$b=_.H(_.E(b,14));c.af=!1;c.name=_.I(_.E(b,2));c.id=_.I(_.E(b,10));c.pf=_.I(_.E(b,4));var d=_.E(b,7);d=null!=d?d.toString():"";var e=1==c.type,f=e?"none":c.id;c.Ze=e?a.Ba==c.ab:a.tb==f;e=(e?a.$:a.kb).replace("$authuser",d).replace("$session_index",d).replace("$pageId",f).replace("$email",c.ab);if(c.$b){d=new _.ih(jz());e=new _.ih(e);f=d.clone();var g=!!e.b;g?_.jh(f,e.b):g=!!e.A;g?f.A=e.A:g=!!e.cb;g?
_.kh(f,e.cb):g=null!=e.B;var k=e.Sa();if(g)_.lh(f,e.B);else if(g=!!e.C)"/"!=k.charAt(0)&&(d.cb&&!d.C?k="/"+k:(d=f.Sa().lastIndexOf("/"),-1!=d&&(k=f.Sa().substr(0,d+1)+k))),k=_.Ts(k);g?_.mh(f,k):g=""!==e.La.toString();g?_.nh(f,e.La.clone()):g=!!e.o;g&&(f.o=e.o);c.Qd=a.Qb.replace("$continue",_.Pc(f.toString())).replace("$email",_.Pc(c.ab))}else c.Qd=e;c.valid=!0}!c.valid||a.w&&!c.$b||(d=ez(a,c),c.$b&&a.o.push(b),fz(a,d,c.type))};
Xy.prototype.Nb=function(a,b){_.Gf(b.target.parentElement);Zy(this);a=iz(this.Ob.replace("$email",a));_.af((0,_.u)(this.Kb,this,a),this.V,this);b.preventDefault();b.stopPropagation()};var iz=function(a){a=_.yh(a);a.La.add("origin",jz());a=_.S("IFRAME",{width:0,height:0,frameborder:0,"class":"gb_bb",src:a.toString()});window.document.body.appendChild(a);return a};
Xy.prototype.Na=function(a){var b=a.target;if(32==a.keyCode||13==a.keyCode){if(_.Wg(b,"gb_Wb")){b.click();a.preventDefault();a.stopPropagation();return}kz(this,a,b)}27==a.keyCode&&null!=b.getAttribute("selected")&&lz(this)};Xy.prototype.Ga=function(a){27==a.keyCode&&(this.B.focus(),lz(this),a.preventDefault(),a.stopPropagation())};Xy.prototype.Pb=function(a){kz(this,a,a.target.parentElement)};
var kz=function(a,b,c){var d=null!=c.getAttribute("selected");lz(a);d||(c.setAttribute("selected","true"),a.B=c,_.O("gb_Xb",c).focus(),mz(c,!1));b.preventDefault();b.stopPropagation()},mz=function(a,b){(0,_.wa)(_.bn(a),function(a){a.setAttribute("aria-hidden",_.Wg(a,"gb_Wb")?b:!b)})},lz=function(a){null!=a.B&&(a.B.removeAttribute("selected"),mz(a.B,!0),a.B=null)},gz=function(a,b,c){c?a.T=b:a.O=b;a.M&&a.C&&(b=!a.T&&!a.O,!b&&_.Wg(a.C,"gb_bb")&&_.af(a.Xa,2E4,a),nz(a,!b))},nz=function(a,b){a.M&&a.C&&
(_.ln(a.C,"gb_bb",!b),a=_.dn(a.C),null!=a&&_.ln(a,"gb_oa",b))};Xy.prototype.Xa=function(){nz(this,!1);this.O=this.T=!1;hz(this)};Xy.prototype.Kb=function(a){null!=a&&_.Gf(a)};var hz=function(a){null!=a.G&&(_.Gf(a.G),a.G=null)};Xy.prototype.Da=function(){var a=new _.Ln;_.T(a,2,"fake user name");_.T(a,3,"fake_debug_email");_.T(a,1,1);_.T(a,10,"11111");_.T(a,6,!1);_.T(a,14,!0);bz(this,a)};
var pz=function(a,b,c,d,e,f){var g=_.If(window);this.H=a;this.G=b;this.D=c;this.M=d;this.K=f;this.o={};_.cq.call(this,"onepick",Ty(oz(this)).toString(),e);_.nt(new _.mt(g),this.o)};_.y(pz,_.cq);
var oz=function(a){var b=a.M.join("-c,")+"-c",c=new Gy;c.b.type="ofuser";var d=new Sy;_.xh(d.b,"profilePhoto","true");_.xh(d.b,"hostId","og");c=Ry(Py(Py(Py(d,new Uy("profile")),new Gy),c),"iframes");_.xh(c.b,"actions","loaded");_.xh(c.b,"thumbs",b);_.xh(c.b,"hl",a.H);_.xh(c.b,"authuser",a.G);_.xh(c.b,"st",a.K);a.D&&_.xh(c.b,"groupId",a.D);0<=_.Ra(_.sf,"10.1")&&Py(c,new Vy("profile","photos"));return c};_.h=pz.prototype;_.h.Bd=function(){return{message:(0,_.u)(this.tc,this)}};
_.h.tc=function(a){this.ga.dispatchEvent(new _.eq("message",[a]))};_.h.Ad=function(){return{onOpen:(0,_.u)(this.Tg,this),onReady:(0,_.u)(this.Ug,this),onClose:(0,_.u)(this.Sg,this)}};_.h.qd=function(a){this.ga=a};_.h.Tg=function(a){this.b=a;this.o.onOpen&&this.o.onOpen(a)};_.h.Ug=function(){_.dq(this,3)};_.h.Sg=function(a){this.o.onClose&&this.o.onClose(a)};
var qz=function(a,b,c,d,e,f){_.z.call(this);this.b=a;this.B=c;this.D=b;this.F=d;this.A=f;this.w=new _.bq(e,this);this.o=_.Mc("op");this.w.L(this.o,"message",this.C)};_.y(qz,_.z);qz.prototype.P=function(){qz.J.P.call(this);this.b&&delete this.b;delete this.B;this.w.ha()};qz.prototype.G=function(a){var b=this.o.b.b;if(b){var c=_.lt(b);if(c&&(_.kt(c,a),a&&(this.A.log(34),(a=b.getIframeEl())&&a.contentWindow)))try{a.focus(),a.contentWindow.focus()}catch(d){}}};
qz.prototype.C=function(a){a=a.w[0];if("picked"==a.action){a=a.docs[0].thumbnails;var b=rz(a,this.D);b&&this.b&&(this.b.style.backgroundImage="url("+b+")");if(a=rz(a,this.F))this.B.style.backgroundImage="url("+a+")";this.A.log(35)}};
var rz=function(a,b){for(var c=0;c<a.length;c++)if(a[c].height==b)return a[c].url;return null},sz={method:"POST",path:"https://people-pa.googleapis.com/v2/people:batchGet",body:{personId:"me",requestMask:{includeField:{paths:"person.photo"},includeContainer:"PROFILE"},extensionSet:{extensionNames:"ABOUT_ME_ADDITIONAL_DATA"},mergedPersonSourceOptions:{includedProfileStates:"CORE_ID"}}},tz=function(a,b,c,d,e,f){this.C=b;this.K=c;var g;_.E(this.C,35)&&(g=a);_.st.call(this,a,"gbd4",d,e,!0,f,g);this.S=
!1;(this.O=_.H(_.E(this.C,30),!1))&&_.H(_.E(this.K,3))&&_.ln(_.O("gb_ob",this.o),"gb_cb",!0);this.qa=this.H=5;this.Ma()};_.y(tz,_.st);_.h=tz.prototype;_.h.P=function(){tz.J.P.call(this);this.D&&this.D.ha();this.N&&this.N.ha()};_.h.close=function(a,b){this.D&&lz(this.D);return tz.J.close.call(this,a,b)};
_.h.Kd=function(){tz.J.Kd.call(this);var a=_.O("gb_Zf",this.o);a&&_.tj(this,a,(0,_.u)(this.Xg,this));(a=_.O("gb_Xf",this.o))&&_.tj(this,a,(0,_.u)(this.wg,this));(a=_.O("gb_0f",this.o))&&_.tj(this,a,(0,_.u)(this.bh,this));(a=_.O("gb_Lb",this.o))&&_.tj(this,a,(0,_.u)(this.Ng,this))};_.h.Ma=function(){tz.J.Ma.call(this);this.B&&this.A(this.B,"focus",this.fh,!1,this)};_.h.Tc=function(a){try{uz(this)}catch(b){}this.G.log(_.Wg(a.target,"gb_eb")?42:43);tz.J.Tc.call(this,a)};
var uz=function(a){_.E(a.C,12)&&a.O&&(a.S||_.H(_.E(a.K,3))&&_.E(a.C,31)&&_.r("gapi.load")("client",(0,_.u)(function(){var a=_.r("gapi.config.update");a("googleapis.config/auth/useFirstPartyAuth",!0);a("googleapis.config/auth/useFirstPartyAuthV2",!0);a("client/cors",!0);_.r("gapi.client.request")(sz).then(this.Wg,this.Uh,this);this.S=!0},a)))};_.h=tz.prototype;
_.h.Wg=function(a){a=a.result.personResponse;0!=a.length&&(a=a[0],null!=a&&(a=a.person.extendedData.aboutMeExtendedData.profileEditability.lockedField,null!=a&&-1!=a.indexOf("person.photo")||vz(this)))};_.h.Uh=function(){this.w.log("Error in loading API.")};_.h.fh=function(){wz(this)};_.h.Xg=function(){this.G.log(10)};_.h.wg=function(){this.G.log(48)};_.h.bh=function(){this.G.log(9,{l:"o"});null!=this.M&&this.M.log(60)};_.h.Ng=function(){this.G.log(49)};
_.h.sc=function(a,b){tz.J.sc.call(this,a,b);1==a&&xz(this)};_.h.open=function(a){xz(this);tz.J.open.call(this,a)};
var yz=function(a){if(!a.D){var b=_.O("gb_Ob",a.o);b&&(a.D=new Xy(b,a.C,a.K,a.w,a.G))}return a.D},xz=function(a){var b=yz(a);a.W?null!=b&&b.w&&b.K&&cz(b):(a.W=!0,null!=b&&cz(b),a.O&&_.H(_.E(a.K,3))||vz(a),wz(a))},vz=function(a){if(_.E(a.C,12)){var b=_.O("gb_Bb",a.o);if(b){try{if(window.location.host!=window.top.location.host)return}catch(g){return}var c=_.O("gb_db",a.b),d=_.J(_.F(a.C,6,30)),e=_.O("gb_Eb",a.o),f=_.J(_.F(a.C,7,96));a.N=new qz(c,d,e,f,a.w,a.G);_.tj(a,b,a.V);_.ln(_.O("gb_ob",a.o),"gb_cb",
!1)}}};tz.prototype.V=function(a){var b=this.N;_.Pq(b.o,(0,_.u)(b.G,b,!0));a.preventDefault()};var wz=function(a){if(a.o&&!a.o.hasAttribute("img-loaded")){for(var b=a.o.getElementsByTagName("img"),c=0,d;d=b[c];c++)d.hasAttribute("data-src")&&(d.setAttribute("src",d.getAttribute("data-src")),d.removeAttribute("data-src"));a.o.setAttribute("img-loaded","1")}};
tz.prototype.X=function(a,b,c,d,e,f,g,k,p,q){var w=yz(this);w.lb.log(44,{n:"paa"});q=q?2:1;a=ez(w,{ab:e,id:"",Ze:a,$e:b,af:c,$b:!1,Qd:f?g||"":"",name:d||"",pf:p||"",type:q});k&&(k["class"]&&(_.Xg(a,k["class"].split(" ")),delete k["class"]),delete k.href,"_blank"==a.target&&delete k.target,_.fd(a,k));f||_.P(a,"gb_1b");fz(w,a,q,!0)};tz.prototype.ca=function(a){az(yz(this),this.fb(),a)};
tz.prototype.$=function(a){for(var b=yz(this),c=this.fb(),d=0;d<b.A.length;d++)_.Gf(b.A[d]);b.A=[];Yy(b,c,a);Zy(b);$y(b,!1)};tz.prototype.ba=function(a){var b=yz(this);b&&gz(b,a)};_.U(function(){var a=!!_.K().yd(),b=_.O("gb_da"),c=_.O("gb_ga");if(a&&b&&c){a=_.Xb();a=_.H(_.E(a,11));c=_.V();var d=_.Oj(),e=_.lj();new By(b,a,c,d,e);(b=_.O("gb_qe"))&&new Cy(b,a,c,d)}});
(function(){var a=_.G(_.K(),sy,10)||new sy,b=_.vi(),c=_.V();a=new pz(_.I(_.E(_.Xb(),5)),_.I(_.E(b,5)),_.I(_.E(b,7)),[_.F(a,6,30),_.F(a,7,96)],c,_.E(a,36)||"");c=new _.Mq(a,_.qp()||new _.jp,c);a=_.Mc("gc");_.Fa("op",c.init(a));_.U(function(){var a=_.O("gb_xb"),b=_.O("gb_jb");a&&b&&a.parentNode!=b&&b.appendChild(a)})})();
_.U(function(){if(_.G(_.K(),sy,10)){var a=_.G(_.K(),sy,10)||new sy;if(!_.H(_.E(a,34))){var b=_.O("gb_jb");if(b){var c=_.vi(),d=_.V(),e=_.Oj(),f=_.lj();a=new tz(b,a,c,d,e,f);_.x("gbar.spd",(0,_.u)(a.open,a));_.x("gbar.paa",(0,_.u)(a.X,a));_.x("gbar.pca",(0,_.u)(a.$,a));_.x("gbar.pcm",(0,_.u)(a.ca,a));_.x("gbar.pti",(0,_.u)(a.ba,a));_.Mc("api").Qa()}}}});
_.U(function(){var a=_.jv();null==a.o&&a.init();_.gv(a,{});_.Mc("api").Qa();a.o.Rd()});var zz=function(a,b,c,d,e,f,g){_.zt.call(this,a,"gbd3",b,c,e,_.J(_.F(d,1,10)),"onShowShareboxOnly","onHoverSharebox",f,g,!0);this.H=3;this.Fa=!0;this.N=[];this.K="gb_Nf";this.S=_.I(_.E(d,3));this.Ma()};_.y(zz,_.zt);zz.prototype.open=function(){if(0<this.N.length){for(var a={},b=!1,c=(0,_.u)(this.ca,this),d=0,e;e=this.N[d];++d)try{var f=e(c);if(f){for(var g in f)a[g]=f[g];b=!0}}catch(k){this.w.log(k)}_.Qq(this.D,"setPrefill",[a,!b])}zz.J.open.call(this)}; zz.prototype.ca=function(a){_.Qq(this.D,"setPrefill",[a])};
window.location.host==window.top.location.host&&_.U(function(){var a=_.O("gb_Mf");if(a){var b=_.V(),c=_.Oj(),d=_.Pp("gb"),e=_.Mc("if"),f=new zz(a,_.qp()||new _.jp,e,_.G(_.K(),ty,8)||new ty,d,b,c);_.x("gbar.asmc",function(a){f.N.push(a)})}});
}catch(e){_._DumpException(e)}
/* _GlobalSuffix_ */
})(this.gbar_);
// Google Inc.
